query AdminMemberMonthCircle($memberId: String!, $year: Int!, $month: Int!) {
  member(id: $memberId) {
    ...ListedMember
    monthCircle(year: $year, month: $month) {
      ...MemberMonthCircle
      locked
    }
  }
}
