query AdminTop {
  thisMonth {
    ...MonthAndSurvey
  }
  nextMonth {
    ...MonthAndSurveyWithMembers
  }
  siteMetadata {
    activeMembers
  }

  signUps {
    ...ListedSignUp
  }

  circles {
    ...ListedCircle
  }
}
