fragment MemberMonthCircle on MonthCircle {
  id
  year
  month
  circle {
    id
    name
  }
}

fragment ListedMember on Member {
  id
  name
  trainerId
}

fragment FullMember on Member {
  id
  pathname
  name
  trainerId
  setupCompleted
  circle {
    id
    name
  }
  circleRole
}
