fragment MonthAndSurvey on Month {
  year
  month
  survey {
    id
    year
    month
    expiredAt
  }
}

fragment MonthAndSurveyWithMembers on Month {
  year
  month
  survey {
    id
    year
    month
    expiredAt
    answeredMembers {
      id
      name
    }
    noAnswerMembers {
      id
      name
    }
  }
}
