fragment MonthAndSurvey on Month {
  year
  month
  survey {
    id
    year
    month
    expiredAt
  }
}

fragment MonthAndSurveyWithMembers on Month {
  year
  month
  survey {
    id
    year
    month
    expiredAt
    answers {
      ...MemberMonthCircle
      member {
        ...ListedMember
      }
    }
    noAnswerMembers {
      id
      name
    }
  }
}
