query MemberMonthCircles($memberId: String!) {
  member(id: $memberId) {
    thisMonthCircle {
      ...MemberMonthCircle
    }
    nextMonthCircle {
      ...MemberMonthCircle
    }
  }
  circles {
    ...ListedCircle
  }
}
