query Setup($pathname: String!) {
  member(pathname: $pathname) {
    ...FullMember
    signUp {
      id
      circle {
        ...ListedCircle
      }
      invited
      joined
    }
  }
  circles(filter: CircleSelect) {
    ...ListedCircle
  }
}
