query Top(
  $memberId: String!
  $thisYear: String!
  $thisMonth: String!
  $nextYear: String!
  $nextMonth: String!
) {
  member(id: $memberId) {
    id
    name
    trainerId
    trainerName
    circleRole
    circle {
      id
      name
    }
    thisMonthCircle: monthCircle(year: $thisYear, month: $thisMonth) {
      ...MemberMonthCircle
    }
    nextMonthCircle: monthCircle(year: $nextYear, month: $nextMonth) {
      ...MemberMonthCircle
    }
  }
}
